name: Build and Push Docker Image

on:
  push:
    branches: main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: True

      - name: Output commit short SHA
        id: short-sha
        run: |
          echo "::set-output name=GITHUB_SHORT_SHA::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Run build script
        run: ./build ${{ steps.short-sha.outputs.GITHUB_SHORT_SHA }}
